### PR TITLE
Remove the Scream Action

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Changelog

:cl:
- remove: I have a mouth but must not scream (removed the scream action in favor of emotes)

### CODE REVIEW

**Review by Pspritechologist — CHANGES_REQUESTED** [review]
I saw we comment out the line where the action is added, undo all the other changes, and *maybe* comment it out of the component as well. There's no need to touch this much Upstream stuff, let alone *without annotation* :astonished:

**Comment by DEATHB4DEFEAT** [comment]
> I say we comment out the line where the action is added, undo all the other changes, and _maybe_ comment it out of the component as well. There's no need to touch this much Upstream stuff, let alone _without annotation_ 😲

[kill it with fire](https://store.steampowered.com/app/1179210/Kill_It_With_Fire/)

**Comment by Pspritechologist** [comment]
Did you take a look at the Component refs to make sure it isn't ever added via any other shenanigans?

**Comment by DEATHB4DEFEAT** [comment]
> Did you take a look at the Component refs to make sure it isn't ever added via any other shenanigans?

Yes

**Review by Pspritechologist — APPROVED** [review]

**Pull request merged**
